### ISSUE TITLE
it's failure to show the new window when i create a new stage in javafx. why?

### ISSUE THREAD

**Issue by qq1440837150** [fvarrui/JavaPackager#102]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

**Steps to reproduce the issue/enhancement:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**What is the expected behavior?**

**What is the current behavior?**

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version:
- OS version:
- JDK version:
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @qq1440837150!

As you mentioned JavaFX, maybe this helps: https://github.com/fvarrui/JavaPackager/issues/20#issuecomment-599055530

Likewise, if you are on Windows, you can display the thrown exception stacktrace using this property:
```xml
<winConfig>
    <headerType>console</headerType>
</winConfig>
```

If it doesn't ... please, could you fill in some of the questions? (because your issue looks like an Agatha Christie novel 😄 ... too mysterious for me)

**Comment by fvarrui** [comment]
Hi @qq1440837150!
Have you found a solution for your issue?

**Comment by qq1440837150** [comment]
Thanks for your help! I have solved this issue.
