### ISSUE TITLE
Generate DEB  or RPM when building with Gradle

### ISSUE THREAD

**Issue by unclezs** [fvarrui/JavaPackager#115]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**

Generate DEB  or RPM when building with Gradle.

I'm looking forward to this feature, and I want to know when it can be implemented.

**Please tell us about your environment:**

- JavaPackager version: v1.6.0-SNAPSHOT
- OS version:  windows 11
- JDK version: openjdk 11
- Build tool: 
	- [ ] Maven 
	- [x] Gradle

**Comment by fvarrui** [comment]
Hi @unclezs!

Sorry! 😢  I've been spending my time in other features and fixing bugs. I've been trying to use [gradle-ospackage-plugin](https://github.com/nebula-plugins/gradle-ospackage-plugin) by Netflix, which allows to generate both RPM and DEB installation artifacts, but I haven't succeeded.

I want to test this [plugin](https://github.com/gesellix/gradle-debian-plugin) in order to generate DEB files, but it would be great to have more alternatives, to select the most suitable. And I'm not sure about RPM artifacts.

I've also been evaluating using the [JDeb](https://github.com/tcurdt/jdeb) library directly, so as not to have to depend on two different plugins depending on the building tool.

Any help will be welcome!

**Comment by fvarrui** [comment]
Hi @unclezs!
DEB files generation is now available for Gradle. Changes released in [issue-115](https://github.com/fvarrui/JavaPackager/tree/issue-115) branch. I finally used jdeb, so the process is the same for Maven and Gradle. Now I'm working in generate RPM files in Gradle.

**Comment by unclezs** [comment]
Thanks a lot！

**Comment by fvarrui** [comment]
RPM file generation is still in process, so I'm going to keep this issue opened until then

**Comment by fvarrui** [comment]
I'm happy to announce that DEB files generation is now available for Gradle. Changes released in [issue-115](https://github.com/fvarrui/JavaPackager/tree/issue-115) branch. I used [RedLine-RPM](https://github.com/craigwblake/redline) library, so the process is the same for Maven and Gradle, as with DEB files. And as both libraries are implemented un pure Java, DEB and RPM files can be generated from different platforms than GNU/Linux.

**Comment by fvarrui** [comment]
issue-115 branch merged into master. Changes will be released in v1.6.0 asap.

**Comment by fvarrui** [comment]
JavaPackager v1.6.0 released to Maven Central
