### ISSUE TITLE
mvn package errors

### ISSUE THREAD

**Issue by gmseed** [fvarrui/JavaPackager#129]
Hi

I followed the installation instructions, and can see that it installed in my local .m2 Maven folder.

When I do a "mvn package" I get a number of errors;

1)

[ERROR]         'iscc' is not recognized as an internal or external command,
[ERROR]         operable program or batch file.
[ERROR]     Setup installer generation failed due to: Command execution failed: iscc /OP:\Software\Java\target /Fqps_1.18.0 P:\Software\Java\target\assets\qps.iss
[ERROR]
org.codehaus.plexus.util.cli.CommandLineException: Command execution failed: iscc /OP:\Software\Java\target /Fqps_1.18.0 P:\Software\Java\assets\qps.iss
    at io.github.fvarrui.javapackager.utils.CommandUtils.execute (CommandUtils.java:19)
    at io.github.fvarrui.javapackager.utils.CommandUtils.execute (CommandUtils.java:25)
    at io.github.fvarrui.javapackager.packagers.GenerateSetup.doApply (GenerateSetup.java:62)
...

2)
[ERROR]         'candle' is not recognized as an internal or external command,
[ERROR]         operable program or batch file.
[ERROR]     MSI merge module generation failed due to: Command execution failed: candle -out P:\Software\Java\target\assets\qps.msm.wixobj P:\Software\Java\target\assets\qps.msm.wxs
[ERROR]
org.codehaus.plexus.util.cli.CommandLineException: Command execution failed: candle -out P:\Software\Java\target\assets\qps.msm.wixobj P:\Software\Java\target\assets\qps.msm.wxs
    at io.github.fvarrui.javapackager.utils.CommandUtils.execute (CommandUtils.java:19)
    at io.github.fvarrui.javapackager.utils.CommandUtils.execute (CommandUtils.java:25)
    at io.github.fvarrui.javapackager.packagers.GenerateMsm.doApply (GenerateMsm.java:59)
    at io.github.fvarrui.javapackager.packagers.GenerateMsm.doApply (GenerateMsm.java:15)
...

and another error which seems to be the same as 2).

And thoughts?

**Comment by fvarrui** [comment]
hI @gmseed!

As you can see in [docs](https://github.com/fvarrui/JavaPackager#generated-artifacts), Setup generation depends on Inno Setup, and MSI and MSM generation depend on WiX Toolset.

You can install both tools easily running next commands as Administrator in CMD or PowerShell:

1. [Install Chocolatey](https://chocolatey.org/install) package manager for Windows, if you don't have it installed yet:

```bash
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

2. [Install Inno Setup](https://community.chocolatey.org/packages/InnoSetup):

```bash
choco install -y innosetup
```

3. [Install WiX Toolset](https://community.chocolatey.org/packages/wixtoolset):

```bash
choco install -y wixtoolset
```

These commands will install both tools and include them in PATH environment variable. Remember that you have to open a new terminal in order to reload PATH variable before running `mvn package`.

That's all!

I hope it helps!

**Comment by gmseed** [comment]
Thanks for your prompt reply. I should try reading the documentation next time ! I missed the "Requires" column on the right hand side of the table. 
Thanks again for your help.

**Comment by fvarrui** [comment]
> I should try reading the documentation next time ! I missed the "Requires" column on the right hand side of the table.

Don't worry! 😄 

Thanks for trying JavaPackager

**Comment by kapilkumar9976** [comment]
Hi, even after doing this,s still candle and light are not available to run with Wix. Why is it not working, or have they been removed? Please help, I'm having the same issue, and I have installed Wixtoolset by following the docs and the version is 6.*
