### ISSUE TITLE
Show Welcome Page in the EXE installer and group the software for the same organization by Group Name

### ISSUE THREAD

**Issue by gmseed** [fvarrui/JavaPackager#130]
Hi
I've looked around this project's pages and can't see a link to a Forum or Discussion Board for users. I find myself having some questions and suggestions but they are not really issues. Or, is here as good a place as anywhere?
Thanks
Graham

**Comment by fvarrui** [comment]
Feel free to open as many issues as doubts you have! 😃

**Comment by fvarrui** [comment]
> 1. In the Windows Specific Properties:
>    https://github.com/fvarrui/JavaPackager/blob/master/docs/windows-specific-properties.md
>    you have:
>    compiler:Languages\Spanish.isl
>    Note how the closing tag should be

Thanks ... Fixed!

> 2. In the Plugin Configurations for Maven:
>    https://github.com/fvarrui/JavaPackager/blob/master/docs/maven/plugin-configuration-samples.md
>    you have the closing text:
>    "As last sample is running on Windows, it's not necessary to specify a JDK when bundling for Windows (it uses current JDK by default). Otherwise, if running on GNU/Linux or Mac OS X, you have to specify a JDK for Windows."
>    Is that correct: "if running on GNU/Linux or Mac OS X, you have to specify a JDK for Windows."?
> 

When you package your app for Windows from MacOS or GNU/Linux, you have to specify a JDK for Windows through the `jdkPath` property, but only if you want to include a custom JRE with your app (`bundleJre=true` and `customizedJre=true`). Also, you can use `jrePath` instead of `jdkPath`, and specify a JRE to bundle with your app (this JRE is not customized/reduced, but a full JRE). JavaPackager is able to generate a reduced JRE for your app (including only those modules that are necessary for your app). This is possible thanks to `jdeps` and `jlink` commands.

> 3) I notice that when I only support English;
> <setupLanguages>
> 	<english>compiler:Default.isl</english>
> </setupLanguages>
> 
> that the installer jumps straight in there. It would be nice to still have a Welcome screen.
> 

Yes! You are right ... ["Welcome page" is disabled by default by Inno Setup](https://jrsoftware.org/ishelp/index.php?topic=setup_disablewelcomepage), but it's possible to include a boolean property in the plugin configuration to enable it. Maybe: `winConfig.disableWelcomePage=true|false`.

> 4) We can specify name, displayName, organizationName, organizationUrl, organizationEmail, etc and when I added these I expected them to appear on the installer Welcome screen allowing the user to know what's being installed and to be click a hyperlink and exit to the app's website. What happens to all of this data that is added?

If you master Inno Setup, it would be great to have a "Welcome page" sample ... if not, don't worry, I'll do some research about this. Thanks for the suggestion. Most of those properties are used once the app is installed, but it didn't occur to me to include them in the installer Welcome page.

Note that JavaPackager generates an `.iss` file which is then passed to the Inno Setup compiler (`iscc`). This `.iss` file is generated from a [Velocity template](https://github.com/fvarrui/JavaPackager/blob/master/src/main/resources/windows/iss.vtl), and you can create your own.

> 
> A question:
> 
> 1. It's common for a Company to have several Products and when installing them to install as such:
> 
> -Program Files -Company -Product1 -Product2
> 
> Is that possible? In my case it added Product1 off Program files: Program Files/Product1, but it would have been nice to have Program Files/Company/Product1. And then let's say I setup a second installer for Product2, would it test to see if Program Files/Company exists and if not create and if so then add?

Yes! I think it's possible ... maybe we can add a new Windows specific boolean property: `winConfig.includeOrgNameInInstallPath` ... or something like this ... so:

- if ` true`:

```ini
[Setup]
...
DefaultDirName=C:\Program Files\Company\Product1
DefaultGroupName=Company\Product1
...
```

- else (as it's working right now):

```ini
[Setup]
...
DefaultDirName=C:\Program Files\Product1
DefaultGroupName=Product1
...
```

> 
> PS. Excuse the above formatting.

PRs are welcome in this project, if you want to collaborate.

Thanks!!!

**Comment by fvarrui** [comment]
JavaPackager v1.6.3 released to Maven Central.

It will be available in a while!
