### ISSUE TITLE
fails while loading native libraries.

### ISSUE THREAD

**Issue by dipeshji** [fvarrui/JavaPackager#138]
While loading a native library(jNativeHook-2.2.1) it fails and gives the error -> 

`/opt/timesheet/libs/libJNativeHook.so (Permission denied)
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/timesheet/libs/libJNativeHook.so (Permission denied)
at com.github.kwhat.jnativehook.GlobalScreen.(GlobalScreen.java:91)`.

Does this plugin load with fat jars?

**Comment by fvarrui** [comment]
Hi @dipeshji!

> While loading a native library(jNativeHook-2.2.1) it fails and gives the error ->
> 
> `/opt/timesheet/libs/libJNativeHook.so (Permission denied) Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/timesheet/libs/libJNativeHook.so (Permission denied) at com.github.kwhat.jnativehook.GlobalScreen.(GlobalScreen.java:91)`.
> 

The problem is that `jNativeHook` needs write permissions to create `/opt/timesheet/libs/libJNativeHook.so`. If you run your app (installed from DEP or RPM) as `root`, it runs fine, as it has write permission on `/opt/timesheet/libs/`. 

I think you should config **jNativeHook** so that it stores and references the native libraries in a user directory (`$HOME/.timesheet` or `$HOME/.jnativehook`) or in a temporary directory (`/tmp`). In short, some directory where the user has write permissions.

> Does this plugin load with fat jars?

Yes, it does. Use `runnableJar` property in order to specify your own JAR (which can be a fat JAR).

**Comment by fvarrui** [comment]
I just realized that if you already distribute your app with the native library (eg `libJNativeHook-2.2.1.x86_64.so`) in ` libs`, it works fine!

**Comment by fvarrui** [comment]
Supposing you are using Maven and your working directory is `${project.basedir}`: 
1. Package your app: `mvn package`.
2. Run your app: `target/timesheet/timesheet` (this makes jNativeHook unpacks native library into `libs`).
3. Create `assets/libs` directory.
4. Copy the unpacked native library `target/timesheet/libs/libJNativeHook-2.2.1.x86_64.so` to `assets/libs`.
5. Add the following to your POM to copy `assets/libs` when packaging:
```xml
<additionalResources>
    <additionalResource>assets/libs</additionalResource>
</additionalResources>
```
6. Package your app again (now it includes the native library in `libs`).
7. Install you app using DEB file ... and now it works fine! (at least, it worked for me ;-D).

> Maybe you can automate steps 1 to 4 when packaging.
