### ISSUE TITLE
No response during installation

### ISSUE THREAD

**Issue by ccc469** [fvarrui/JavaPackager#140]
![image](https://user-images.githubusercontent.com/27529250/150446885-f32c607a-a636-43e0-ac93-f5a54070a19d.png)

hello,  Click DMG or PKG to install. There is no other response, My system version 10.15.7 Catalina

**Comment by fvarrui** [comment]
Hi @ccc469!

> ![image](https://user-images.githubusercontent.com/27529250/150446885-f32c607a-a636-43e0-ac93-f5a54070a19d.png)

Actually this is not an error, but the DMG customization script shows this message in the error output.

> hello, Click DMG or PKG to install. There is no other response, My system version 10.15.7 Catalina

Please, fill in the error template so we can help you.

**Comment by fvarrui** [comment]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**



**Steps to reproduce the issue/enhancement:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**What is the expected behavior?**



**What is the current behavior?**



**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**



**What is the motivation / use case for changing the behavior?**



**Please tell us about your environment:**

- JavaPackager version:
- OS version:
- JDK version:
- Build tool: 
	- [ ] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)
