### ISSUE TITLE
App doesn't run on MacOS

### ISSUE THREAD

**Issue by ccc469** [fvarrui/JavaPackager#141]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**

**Steps to reproduce the issue/enhancement:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**What is the expected behavior?**

**What is the current behavior?**

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version:  17.0.1
- OS version: MacOS 10.15.7 Catalina
- JDK version:   
      java version "17.0.1" 2021-10-19 LTS
     Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
     Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

_Originally posted by @fvarrui in https://github.com/fvarrui/JavaPackager/issues/140#issuecomment-1020006453_

**Comment by ccc469** [comment]
[files.zip](https://github.com/fvarrui/JavaPackager/files/7929888/files.zip)
Hi, Relevant files are in zip,  Please help me 😊

**Comment by fvarrui** [comment]
Hi! 
Have you tried to run your installed app from the command line?

```bash
/Applications/javafx-demo.app/Contents/Home/MacOS/universalJavaApplicationStub
```

**Comment by fvarrui** [comment]
If when you run your app from command line, you see something like `Error: JavaFX runtime components are missing, and are required to run this application`, the problem is that you have to specify JavaFX modules to the JVM.

### Solution 1: pass `--module-path` and `--add-modules` params to JVM

```xml
<vmArgs>
    <vmArg>--module-path libs/*</vmArg>
    <vmArg>--add-modules javafx.controls,javafx.fxml</vmArg>
</vmArgs>
```

> Above params are passed to "java". :warning: I've not tested this.

### Solution 2: (the easiest in my opinion) use another class as main class

1. Create a new class (e.g. `Main`) which not extends `Application` with a `main` method.
2. Call `App.main` (`App` extends `Application`) method from `Main.main`.
3. Now run the app calling `Main.main`.
3. That's all!

```java
public class HelloApplication extends Application {
    [...]
    public static void main(String [] args) {
        launch(args);
    }
    [...]
}
```

```java
public class Main {
    public static void main(String [] args) {
        App.main(args);
    }
}
```

Now, you `mainClass` would be `Main`, not `App`.

`<mainClass>com.example.javafxdemo.Main</mainClass>`

~~`<mainClass>com.example.javafxdemo.HelloApplication</mainClass>`~~

This solves the problem.

**Comment by ccc469** [comment]
![image](https://user-images.githubusercontent.com/27529250/150894744-274e5634-bf88-46ce-875b-fbfee3ff8320.png)
Hi, I try to run according to your suggestion and return the result, 
Is this a packaging configuration problem in my project?
![image](https://user-images.githubusercontent.com/27529250/150895096-1453ace1-239c-47ee-aadd-631854dee956.png)

**Comment by fvarrui** [comment]
I anticipated the situation 😅  ... please, try what I explained above.

**Comment by ccc469** [comment]
According to your suggestion, the application can be installed and opened normally. Why?

**Comment by fvarrui** [comment]
Did it work? 

> According to your suggestion, the application can be installed and opened normally. Why?

It's a trick 😅 . I'm not sure, I discovered it by accident, but I guess it has to do with the ClassLoader.

**Comment by fvarrui** [comment]
This question is asked a lot here, but it really has nothing to do with JavaPackager... Please, could you share your project to use as an example for future users? It would allow me to improve the documentation of the project.

**Comment by ccc469** [comment]
![image](https://user-images.githubusercontent.com/27529250/150897866-ac07cbdc-51aa-498c-944d-3db4637b090c.png)
I solved my problem according to scheme 2，At least it works in my environment

**Comment by fvarrui** [comment]
Happy to help! I'm it works in any environment 😄

**Comment by ccc469** [comment]
Hi, I still have some questions to ask you. Most of my customers use windows. How can I generate a complete one click installation package like DMG / PKG? The customer's computer may not install JRE environment. Please help me if there are examples

**Comment by fvarrui** [comment]
> According to your suggestion, the application can be installed and opened normally. Why?

I found an explanation ... follow this [link](https://stackoverflow.com/questions/52653836/maven-shade-javafx-runtime-components-are-missing/52654791#52654791).

**Comment by fvarrui** [comment]
> Hi, I still have some questions to ask you. Most of my customers use windows. How can I generate a complete one click installation package like DMG / PKG? The customer's computer may not install JRE environment. Please help me if there are examples

You have to generate an EXE installer (setup) or a MSI file, so your customers can easily install your app. You also can bundle a customized JRE (reduced/optimized) with your app, so your customers don't need to have Java installed on their systems. JavaPackager uses Inno Setup to generate EXE installers and WiX Toolset to generate MSI files, so that if you need these installation artifacts, you have to package your app from a Windows system.

If you don't need the EXE installer or MSI file, JavaPackager can generate a portable (compressed) application from MacOS for Windows. You just have to give JavaPackager the path to a Windows JDK. The portable version may also include a JRE, but users must unzip your application before they can use it.

**Comment by ccc469** [comment]
Thank you!
