### ISSUE TITLE
Mac app bundle won't start: icon bounces in the dock then disappears

### ISSUE THREAD

**Issue by ogerardin** [fvarrui/JavaPackager#149]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

Mac app bundle won't start: icon bounces in the dock then disappears.

**Steps to reproduce the issue/enhancement:**

1. Configure plugin to generate a Mac bundle
2. Build the project 
3. Try to run generated .app bundle

**What is the expected behavior?**

App starts...

**What is the current behavior?**

Icon bounces for a second in the dock then disappears.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

The following message is displayed several times in the console when trying to start the app:
`error	02:20:37.938059+0100	Finder	error finding potential wrapper bundle for node <FSNode 0x600002ad0d40> { isDir = ?, path = <private> }: Error Domain=NSOSStatusErrorDomain Code=-10811 UserInfo={_LSLine=1579, _LSFunction=<private>}
`
You can get the artifact from here: https://github.com/ogerardin/xpman/releases/tag/1.0-SNAPSHOT

**Please tell us about your environment:**

- JavaPackager version: 1.6.3
- OS version: macOS 12.2.1
- JDK version: 11
- Build tool: 
	- [X] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

Artifacts were generated on CircleCI but the same happens when I build locally on my Mac.

Interestingly:
- If I right-click on the .app then "Show package contents" and double-click on `Contents/MacOS/universalJavaApplicationStub` it runs!
- Also if I open terminal, cd into `X-Plane Manager.app/Contents/Resources` and run `java -jar xpman-fx-dist-1.0-SNAPSHOT-repackaged.jar` it runs!
- If I right-click on the jar and select Open with / JavaLauncher it runs!

Relevant pom section: https://github.com/ogerardin/xpman/blob/java11/xpman-fx-dist/pom.xml#L390
Relevant Maven log: https://app.circleci.com/pipelines/github/ogerardin/xpman/79/workflows/cdc1f524-1ddb-46ab-90b1-37e735881309/jobs/219?invite=true#step-106-2468

**Comment by fvarrui** [comment]
Hi @ogerardin!
I'm not being able to build your app ... I run into the next error:

![image](https://user-images.githubusercontent.com/4354486/155127536-559f7973-deae-4c99-8c97-984c72f50bed.png)

I'm executing `mvn package` in the root of your project. Maybe you can throw some light about this, please.

**Comment by ogerardin** [comment]
> I'm executing `mvn package` in the root of your project. Maybe you can throw some light about this, please.

NullPointer in the compiler plugin, that's weird!

I see you're using Maven 3.6.1, Maybe try with Maven 3.8.4, this is what I'm using locally and this is what the CI pipeline uses on all platforms.

**Comment by fvarrui** [comment]
Yes ... I've just realized and upgraded Maven, but same error

**Comment by fvarrui** [comment]
I'm going to download your DMG artifact and try it.

**Comment by fvarrui** [comment]
> Icon bounces for a second in the dock then disappears.

Same behaviour 😮

**Comment by ogerardin** [comment]
> Yes ... I've just realized and upgraded Maven, but same error

Oh wait, I think you're compiling the master branch, this is on the java11 branch...

**Comment by ogerardin** [comment]
> > Icon bounces for a second in the dock then disappears.
> Same behaviour 😮

OK that's a good thing ;)

**Comment by fvarrui** [comment]
> > Yes ... I've just realized and upgraded Maven, but same error
> 
> Oh wait, I think you're compiling the master branch, this is on the java11 branch...

Yes ... was that! 😅

**Comment by fvarrui** [comment]
When I run the app from command line, I'm getting this error:

![image](https://user-images.githubusercontent.com/4354486/155134760-db2b986d-f665-4c01-a354-779bcb387697.png)

When I run the app directly using `universalJavaApplicationStub` script also crashes and shows another error (which seems to be caused by whitespaces ... I have to go deeper into this matter):

![image](https://user-images.githubusercontent.com/4354486/155135284-92aa6155-01b8-4af7-bed3-df580da8ff39.png)

**Comment by fvarrui** [comment]
I've also tried to remove whitespaces from your app name, but still crashes.

**Comment by fvarrui** [comment]
> When I run the app directly using `universalJavaApplicationStub` script also crashes and shows another error (which seems to be caused by whitespaces ... I have to go deeper into this matter):

Ok, I've added double quotes to some variables between lines 318 and 323 in `universalJavaApplicationScript` in order to support whitespaces and now runs fine directly from script:

![image](https://user-images.githubusercontent.com/4354486/155136633-4343f3f1-2d8e-4696-a71a-09c2e34bb179.png)

**Comment by fvarrui** [comment]
> I could probably make things more simple by removing whitespace in the name but I think it's a good test case :)

😅  nooo, don't worry ... I think there's another problem and it seems to be related to `Info.plist` file, but I can't find it.

**Comment by fvarrui** [comment]
I've been making several changes in your project, in order to find out what's happening ... without success! 😞 

I'll keep trying tomorrow ... I'm almost sure that it's something related to `Info.plist`, because the app is not showing the appropriate icon.

![image](https://user-images.githubusercontent.com/4354486/155392002-57f44eef-b2d5-450a-9ccf-a1dcbec5bafb.png)

**Comment by fvarrui** [comment]
> I'm almost sure that it's something related to Info.plist, because the app is not showing the appropriate icon.

I was wrong! After some researching I think I found the problem (at leaset, one of them).

I remember that `universalJavaApplicationStub` script writes in System log:

![image](https://user-images.githubusercontent.com/4354486/155411324-4c56c141-07a7-473d-aae2-3c3c1be281db.png)

Analyzing log entries, I found one that contains the command executed to run the Java app:

![image](https://user-images.githubusercontent.com/4354486/155411530-f1517f39-f7e6-4c0a-b69f-f785a29f5a5d.png)

I copied and ran it in a terminal, printing the next result:

![image](https://user-images.githubusercontent.com/4354486/155411785-2cb3ec90-f720-4a7c-8b8a-4c951b5668b5.png)

From here I could deduce that it's not able to find some Java core classes (`org.xml.sax.InputSource` class owns to [`java.xml` module](https://docs.oracle.com/javase/9/docs/api/java.xml-summary.html)) ... **but why?**

Taking a look to JavaPackager output, we can see that when bundling a customized JRE, `jdeps` only find two dependant modules: `java.base` and `java.logging`:

![image](https://user-images.githubusercontent.com/4354486/155412223-d6fcb5dd-51d3-40c5-b57b-f89064d2e432.png)

 ... and, **where is `java.xml`?** 

Probably, when creating the FAT JAR, `module-info` is being overwritten and this info is lost.

**But, why can we run the "runnable" JAR directly?** 

Because we are using the installed JRE (full, with all modules), not the bundled one (without java.xml module).

**And what can we do now?**

Bundle a full JRE with the app using this property when packaging: `<customizedJre>false</customizedJre>`. I've included this property, build your app, and now it runs fine.

There's another problem with the ICNS file, as it's not properly shown, but this is another story.

I hope it helps!

**Comment by ogerardin** [comment]
Oh great ! I hadn't seen the logs from universalJavaApplicationStub as I had the "errors only" filter on :(

Anyway you're right, if I disable customizedJre it works... 

Regarding module-info: my app has 2 modules: an API and the GUI. Each one has its own module-info. When creating the fat jar (using spring-boot-maven-plugin) those 2 modules get packaged nicely as jars inside the fat jar in the BOOT-INF/lib directory, and I can see that each one has its module-info. However, the fat jar is generated in a third Maven module, dedicated to packaging. Could this be the reason why jdeps is confused?

Thanks a lot for helping! I'll try to dig into this jdeps issue.

**Comment by ogerardin** [comment]
BTW the icon is fine on my Max, not sure what's happening.
![Screenshot 2022-02-24 at 00 52 45](https://user-images.githubusercontent.com/110559/155430471-bc8bf256-7515-4965-b059-3f22b99f289f.png)

**Comment by fvarrui** [comment]
`jdeps` has been my biggest headache with JavaPackager... I'm not able to master it! With each version the options and output change, it often fails saying it can't find the necessary modules when analyzing libraries, etc. but for now it's the only thing that I have found so far to be able to determine the necessary modules to generate an optimized JRE with `jlink`.

If you know which core modules your app needs, you can use `modules` property, so `jdeps` call is skipped. Sorry! 🤷‍♂️

**Comment by ogerardin** [comment]
These seems to hit the same issue: 
https://stackoverflow.com/questions/53975829/how-to-use-jdeps-to-analysis-dependency-of-a-fat-jarspring-boot
https://stackoverflow.com/questions/59869897/jlink-spring-boot
https://stackoverflow.com/questions/67823281/java-jdeps-command-on-a-springboot-jar-throws-error-for-tomcat-dependency
They all suggest unpacking the jar to run jdeps...

I could probably run a step to do that automatically before javapackager is invoked, but as this won't change often it's probably best to just run jdeps outside the build and harcode the modules as you suggested.

**Comment by ogerardin** [comment]
Closing this issue as the cause has been found and there's not much JavaPackager can do about it.
