### ISSUE TITLE
Command execution failed (due to spaces in path)

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#219]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

`Command execution failed: codesign --force --options runtime --deep --entitlements /Volumes/Case-sensitive Volume/sources/myapp/target/assets/entitlements.plist --sign <my-developer-id> /Volumes/Case-sensitive Volume/sources/myapp/target/MyApp/MyApp.app`

If I manually make the call and enquote the path, I can execute codesign successfully.

**Steps to reproduce the issue/enhancement:**

1. Configure developer-id and app-id in the mac-specific config
2. Run mvn clean package

**What is the expected behavior?**

Build should succeed

**What is the current behavior?**

Build failes 

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version:
- OS version:
- JDK version:
- Build tool: 
	- [X] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Thanks for the PR!!! 

I'm glad to see that you were able to find and fix the problem ... I hope the way the JavaPackager code is organized helped you 😃

**Comment by fvarrui** [comment]
Hi @kerner1000!
Adding single quotes is not working for me 😢 

![image](https://user-images.githubusercontent.com/4354486/178598478-175894cf-9b9a-46ab-ae68-4ccdd48f01c8.png)

![image](https://user-images.githubusercontent.com/4354486/178598938-c0e7e9cf-3e65-42a4-a09e-f175966d7d6e.png)

A picture (or two) is worth a thousand words. 

I've also tried with `devel` branch and it worked fine!! 

![image](https://user-images.githubusercontent.com/4354486/178599912-be9eb112-1606-46d6-b3df-b132f2f78dae.png)


Please, can you share Maven output? At least at least the part where the error message appears. Maybe the problem is other than spaces in path.

Thanks!!!

**Comment by kerner1000** [comment]
Hi @fvarrui, thanks for your time! And thanks for the screenshot, it indeed is very clarifying.
I double checked and it seems arguments are per default double-quoted. Only in the error message they are not, strangely.
The codesign is failing for some other reason..
![Screenshot 2022-07-13 at 08 50 12](https://user-images.githubusercontent.com/13817521/178669737-66a9c91b-1f65-4707-aff7-f91aa1767ae3.png)

**Comment by fvarrui** [comment]
Hi @kerner1000!
I really don't know what the problem is, but it seems that your certificate is not valid.
Maybe [this article](https://ceyhunkeklik.medium.com/how-to-fix-ios-application-code-signing-error-4818bd331327) could be helpful. It says that a Mac OS update may cause problems with duplicate certificates. I'm not sure if this is the case, but maybe you can try it. Likewise, the article also proposes other solutions to the problem of `errSecInternalcomponent`.

**Comment by kerner1000** [comment]
Hi @fvarrui ,
thanks so much for support! I got the signing issue somehow resolved (it seems), the build succeeds. Now I have trouble to upload the binary to the app store.

![Screenshot 2022-07-13 at 15 13 35](https://user-images.githubusercontent.com/13817521/178742250-9b850651-e834-4675-9a95-3499d745c9f3.png)

Was trying all IDs ("Bundle ID", "SKU", "Apple ID") for "appId", but somehow it still seems to be wrong. :(

![Screenshot 2022-07-13 at 15 15 20](https://user-images.githubusercontent.com/13817521/178742948-49bb45a4-8c8d-45e2-b204-e02cd29811e1.png)

Packaging and deploying to the App store really is an adventure. It took me already more time than to write the app itself :D

**Comment by fvarrui** [comment]
There's no victory without pain! 😅 

I'm sorry, but I've never released an app to the AppStore ... I don't even have an Apple Developer ID 😥. 

Maybe you should notarize the app before uploading to the AppStore.
