### ISSUE TITLE
Custom Info.plist template not used

### ISSUE THREAD

**Issue by bdemers** [fvarrui/JavaPackager#28]
I created a `<project-root>/assets/macosx/Info.plist.vtl` file (based on the default velocity template), and it's not getting picked up.  Is this expected?

I'm probably reading the code wrong, but it looks like the velocity templates are just pulled from the plugin classpath.

**Comment by fvarrui** [comment]
Hi again @bdemers,

> I created a <project-root>/assets/macosx/Info.plist.vtl file (based on the default velocity template), and it's not getting picked up. Is this expected?

Sorry! There was an error on README doc. Assets folder for Mac OS X has to be called `mac`, so you have to use in your case:
`<project-root>/assets/mac/Info.plist.vtl `.

> I'm probably reading the code wrong, but it looks like the velocity templates are just pulled from the plugin classpath.

Velocity templates were getting picked up from plugin classpath because it could't find templates in `assets\mac` folder.

You were doing right! Documentation was wrong, sorry.

Thanks for using JavaPackager and for your feedback!

**Comment by bdemers** [comment]
That was it! thanks for the quick update @fvarrui!
