### ISSUE TITLE
Icon file is not changed in windows

### ISSUE THREAD

**Issue by skwee357** [fvarrui/JavaPackager#428]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

I'm trying to set an icon on windows, but no matter what I try I get the following warning:

```
[INFO]         Icon file resolved: C:\Users\tinyp\workspace\my-app\src\main\resources\icon.ico
[WARNING]         Skipped adding the icon file as additional resource because the target platform is Windows
```

And the icon never changes and stays the default coffee mug. I tried to put the icon in `assets`, in `src`, provider the `icoFile` attribute with the path to the icon, but the icon does not change after packaging the app. Neither for the installer, nor for the executable.

Host is Windows, target is windows.

**Please tell us about your environment:**

- JavaPackager version: 1.7.6
- OS version: Windows 11
- JDK version:
- Build tool: 
	- [x] Maven 
	- [ ] Gradle

**Comment by fvarrui** [comment]
Hi @skwee357!
Windows Explorer caches icons and I guess it's showing the previous EXE icon instead of the new one. Please, see EXE file properties and check if it shows same icon or the right one.

To fix this, just remove all contents in Explorer cache folder: C:\Users\%username%\AppData\Local\Microsoft\Windows\Explorer. Maybe you also have to kill Explorer process and run it again

**Comment by skwee357** [comment]
Thanks @fvarrui , it was indeed the issue! Didn't know that. Appreciate your fast response!
