### ISSUE TITLE
dmg file not generated

### ISSUE THREAD

**Issue by uwemock** [fvarrui/JavaPackager#5]
I tried the JavaPackager as a replacement for sh.tak.appbundler and replaced all the configuration switches with the new ones. I get a successful build, but no dmg file. However, I have this in my configuration:

```
 <dmg>
    <generate>true</generate>
    <createApplicationsSymlink>true</createApplicationsSymlink>
</dmg>
```

**Comment by fvarrui** [comment]
Please, could you provide me with the full JavaPackaher plugin configuration? What system are you building on? Thanks!

**Comment by fvarrui** [comment]
Thanks for your quick reply! Sorry, but if you want to generate a DMG file you have to run the build on a Mac OS X system, because JavaPackager uses "hdiutil" (a Mac command) in order to generate it.

And the plugin config you have provided doesn't seem to be for JavaPackager maven plugin. Take a look to the [README](https://github.com/fvarrui/JavaPackager/blob/master/README.md) file. If you explain to me what are you trying to do with JavaPackager, maybe I could help you.

**Comment by uwemock** [comment]
Sorry, it seems I got lost during my search for a replacement for sh.tak.appbundler...

**Comment by fvarrui** [comment]
Tell me what you need and maybe JavaPackager could fit your expects.
