### ISSUE TITLE
Use JavaPackager from Gradle

### ISSUE THREAD

**Issue by bbousquet74** [fvarrui/JavaPackager#52]
Greetings,

I understand, from looking at the commits, that this is on the roadmap. I have a Java desktop app (running with OpenJDK 8u265) that requires packaging, specifically on macOS for now. I used to rely on Oracle JDK 8u192's built-in javapackager but that is not part of OpenJDK and I can't have the Mac DMG notarized by Apple with 8u192. Our app is built with Gradle.

Regards.

**Comment by fvarrui** [comment]
Hi @bbousquet74!

Thanks for your interest in JavaPackager.

> Greetings,
> 
> I understand, from looking at the commits, that this is on the roadmap. 

Yes, I'm working on an hybrid plugin (which works for Maven and Gradle) ... I'm on first steps (decoupling plugin's business logic from Maven) and I'm not sure when I'll have a testable version, but the project is not stuck. The most difficult thing is to find a substitute in Gradle for the Maven plugins that are invoked internally by JavaPackager, but I'm on it.

> I have a Java desktop app (running with OpenJDK 8u265) that requires packaging, specifically on macOS for now. I used to rely on Oracle JDK 8u192's built-in javapackager but that is not part of OpenJDK and I can't have the Mac DMG notarized by Apple with 8u192. Our app is built with Gradle.
> 

I encourage you to test it on Maven, so that you can check if the generated DMG is valid for you.

> Regards.

We can leave this issue opened, so when I've got something testable I can let you know.

Regards!

**Comment by bbousquet74** [comment]
¡Muchas gracias para la respuesta!

I'll be watching this thread.

**Comment by fvarrui** [comment]
¡De nada!

**Comment by fvarrui** [comment]
Hi @bbousquet74 !

I'm happy to announce that [JavaPackager version 1.2.0 is also available for Gradle](https://github.com/fvarrui/JavaPackager#config-your-project-and-package-your-app-with-gradle).

I hope it works fine and meet your needs.

Thanks!

**Comment by bbousquet74** [comment]
Thank you for the follow-up!
