### ISSUE TITLE
[error] '"C:\Program Files\Java\jdk1.8.0_211\jre\bin\jlink"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mudiadamz** [fvarrui/JavaPackager#6]
[error] '"C:\Program Files\Java\jdk1.8.0_211\jre\bin\jlink"' is not recognized as an internal or external command

**Comment by fvarrui** [comment]
JavaPackager generates an optimized/reduced Java runtime environment for your app with `jlink`, in order to bundle it with your app, but it only works with JDK9+. It may works with Java 8 if you use `<bundleJre>false</bundleJre>` option, but JRE won't be bundled. However, I think it's possible to extend JavaPackager for copying the entire `jre` folder from your JDK (C:\Program Files\Java\jdk1.8.0_211 in this case) to bundle it with your app, only when detects that you are using JDK8-. Thanks for giving a try to JavaPackager!

**Comment by mudiadamz** [comment]
so there's no plan to support jdk 8? I've tried java 9+ for my projects several times and end-up frustating myself

**Comment by fvarrui** [comment]
Don't worry, I think it's easy to add support for JDK8 as I told you before: copying the entire jre folder into the bundle.

**Comment by fvarrui** [comment]
I've been doing some research and depending on the JDK provider, the JRE may be located in different places. If I could find out programatically where the current JRE is installed (independently from the JDK provider or operating system), it'd be very easy.  Would you be worth an option in the plugin config where you specify the path to the directory where the JRE is installed? For instance: `<jrePath>c:\Program files\Oracle\Java\jre1.8.0_211</jrePath>`, so if you specify this option, the use of `jlink` wouldn't be necessary, and JRE would be added to the bundle from this path.

**Comment by mudiadamz** [comment]
To be honest i don't understand what `jlink `did, yes adding `jrePath `option would be ok for me. i just want to bundles my project into single executable installer, and JRE is bundled inside, no need user to installed java separately.

**Comment by fvarrui** [comment]
I've added `jrePath` option to the plugin. Try version 0.8.3. If it works and solves your problem, I'll close this issue. Please, don't forget to star this project! Thanks.
