### ISSUE TITLE
Impossible to generate two Windows executables

### ISSUE THREAD

**Issue by kascoder** [fvarrui/JavaPackager#64]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue:**
On packageMyApp task execution, the next error is thrown:
Cannot add task 'jplaunch4j' as a task with that name already exists.

**Steps to reproduce the issue/enhancement:**
[Project Zip Archive](https://drive.google.com/file/d/14HCel1V7rXs7AIx-7upjJa4nTQTuPJkG/view?usp=sharing)

**Please tell us about your environment:**

- JavaPackager version: 1.3.0
- OS version: Windows 10 Pro N
- JDK version: OpenJDK 11
- Build tool: 
	- [ ] Maven 
	- [X] Gradle

**Comment by fvarrui** [comment]
Hi @kascoder!
I think it's fixed in v.1.4.0-SNAPSHOT.  I've tried with your attached project and it works fine. I'll release v1.4.0. to Maven Central asap. You can [install snapshot version manually](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin) in order to test it.
Thanks!

**Comment by fvarrui** [comment]
I forgot it! You must use local Maven repository for JavaPackager in order to test the snapshot version:
```groovy
buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath 'io.github.fvarrui:javapackager:1.4.0-SNAPSHOT'
    }
}
```
