### ISSUE TITLE
Mac package prompts users to install Java 6

### ISSUE THREAD

**Issue by keastrid** [fvarrui/JavaPackager#68]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
(Hello again)
Running the package via the zipBall on a different machine from the one that built it prompts the user to install Java 6.

**Steps to reproduce the issue/enhancement:**

1. Open the app file

**What is the expected behavior?**
Using the bundled JRE.

**What is the current behavior?**
Prompts the user to install Java 6

**Please tell us about your environment:**

- JavaPackager version: 1.4.0-SNAPSHOT
- OS version: MacOS 10.15
- JDK version:15
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)
Example zipBall: http://www.astro.louisville.edu/software/astroimagej/updates/AstroImageJ-dev-x86-mac.zip
Repo: https://github.com/keastrid/astroimagej

**Comment by keastrid** [comment]
Manually running `/Applications/AstroImageJ.app/Contents/MacOS/startup` via terminal properly opens the app, but double clicking does not.

**Comment by keastrid** [comment]
Found a somewhat related SO answer with a possible solution: https://stackoverflow.com/a/16592948
Renaming the Java dict key to JavaX did work to fix this issue, but brought an issue of "no MainClass specified"
Updating https://github.com/fvarrui/JavaPackager/blob/cac191190c8b4561ebeadc5b7a2ef2e1c91688a8/src/main/resources/mac/Info.plist.vtl#L41 to be `JavaX` should resolve the issue, see also https://github.com/tofi86/universalJavaApplicationStub/issues/9

**Comment by fvarrui** [comment]
I've just reproduce your issue on a brand new MacOS VM.
![image](https://user-images.githubusercontent.com/4354486/97790802-a83bdc00-1bc3-11eb-8ea0-144e464742c9.png)
And you are right ... running `startup` script from terminal works fine. I think it's because when running the app via double clicking or `open ./AstroImageJ.app` command, the system finds the `Java` key in `Info.plist` file (Apple style) and tries to run it using an installed JRE, ignoring the `CFBundleExecutable` key. So, if there's no JRE installed, it shows this message.

I've changed `Info.plist` file to Oracle style as explained [here](https://github.com/tofi86/universalJavaApplicationStub#supported-plist-keys) and I think it's fixed.

I hope it's fixed, because it has been a headache! 😅

**Comment by keastrid** [comment]
Tested and it seems to work now! Thank you!
