### ISSUE TITLE
Mac app cannot run due to security reasons

### ISSUE THREAD

**Issue by keastrid** [fvarrui/JavaPackager#78]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
After updating from 1.4.0-SNAPSHOT to 1.4.0 (then again to 1.4.1), the generated mac app will not run and will simply close. When running it via Terminal, this is the error provided `LSOpenURLsWithRole() failed with error -10810 for the file <blah app>`.
This error exists whether or not an entitlements file is provided.

**Steps to reproduce the issue/enhancement:**

1. Build a mac app
2. Attempt to run it

**What is the expected behavior?**
It opens.

**What is the current behavior?**
It does not open.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
Some affected builds: https://github.com/keastrid/astroimagej/actions/runs/377841896

**Please tell us about your environment:**

- JavaPackager version: 1.4.1
- OS version: MacOS
- JDK version: 15
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @keastrid!
I've seen that you are using a [customized template for `Info.plist`](https://github.com/keastrid/astroimagej/blob/master/packageFiles/assets/mac/Info.plist.vtl). Your template uses Oracle mode, and v1.4.1 uses Apple mode, so the `universalJavaApplicationStub` script is looking for the `Contents/Java` folder instead of `Contents`:
![image](https://user-images.githubusercontent.com/4354486/99920540-3109eb80-2d1c-11eb-8604-131aa655ff6c.png)

**Comment by keastrid** [comment]
The custom template is needed to change `BNDL` to `APPL` for the script that signs and notarizes the packages (not sure on the specifics as it's not my script).

Updating the template seems to have fixed it though, thanks!
