### ISSUE TITLE
Code signing Windows binaries and installer

### ISSUE THREAD

**Issue by willfurnell** [fvarrui/JavaPackager#82]
I'm submitting a…

- [ ] bug report
- [X] feature request
- [ ] other

**Short description of the issue/suggestion:**
I'd like to be able to code sign both the Windows executable that JavaPackager generates and additonally the installer - the former being more important than the latter, as whilst I could manually code sign the installer after the execution has run, the .exe it packages up won't be signed to my knowledge. 

**What is the motivation / use case for changing the behavior?**
Applications may need to be signed to run on user systems. It also increases trust when installing and running executables.

**Please tell us about your environment:**

- JavaPackager version: 1.4.2
- OS version: Windows 10
- JDK version: 11
- Build tool: 
	- [X] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

It looks like Inno Setup has built in support for signing both the installer and the files inside it - https://jrsoftware.org/ishelp/index.php?topic=setup_signtool - so perhaps this might be of use?

Thank you!

**Comment by fvarrui** [comment]
Hi @willfurnell!

I've been looking into it and as far as I've been able to figure out Inno Setup doesn't sign the installer itelf, but it uses an external tool. Likewise, it doesn't seem to sign the inner executable.

I think that a better aproach could be using [jsign](https://ebourg.github.io/jsign/), because we can use it both to sign the installers (Setup and MSI) and the application executable, and it's implemented in Java, so we don't need another external tool to sign EXE files, can use it both for Gradle and Maven, and can sign the app executable from any platform (Windows, MacOS and Linux).

As soon as I publish a SNAPSHOT version with this new feature I let you know.

Thanks!

**Comment by fvarrui** [comment]
Hi @willfurnell!
Windows binaries and installation artifacts could be signed now with JavaPackager v1.4.3-SNAPSHOT.

Please, take a look to [docs](https://github.com/fvarrui/JavaPackager/blob/master/docs/windows-specific-properties.md#signing-properties) and try it.

If it works fine for you, I'll release it as v1.5.0 to Maven Central.

Thanks!

**Comment by willfurnell** [comment]
Thank you very much! I can confirm that the .exe installer and installed .exe are code signed :)

**Comment by fvarrui** [comment]
v1.5.0 released to Maven Central
