### ISSUE TITLE
Created Exe-File does not run in cmd or cygwin bash

### ISSUE THREAD

**Issue by hannesN** [fvarrui/JavaPackager#96]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
I create a command line tool using the javapackager. However I can only start it in the git-bash. Cygwin and cmd won't start it at all. 

**Steps to reproduce the issue/enhancement:**

1. Create a java program and build it with maven using the javapackager
2. Run the resulting exe in a cmd-shell

**What is the expected behavior?**
 The program is started and its output is seen.

**What is the current behavior?**

Just the next line with a prompt is shown.
Same behavior in cygwin shell.

System: I built with oracles jdk 15.02

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.5.1
- OS version: Windows 10
- JDK version: Oracle JDK 15.02
- Build tool: 
	- [x] Maven  2.6.3
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @hannesN!
Is your application for GUI or for console?

[There's an option for changing the EXE behaviour](https://github.com/fvarrui/JavaPackager/blob/master/docs/windows-specific-properties.md#exe-creation-properties): `winconfig.headerType`. If your app is for GUI, you have to use `headerType=gui` (this is the default value):

```xml
<winConfig>
    <headerType>gui</headerType>
    ...
</winConfig>
```

Otherwise, you have to use `headerType=console`.

```xml
<winConfig>
    <headerType>console</headerType>
    ...
</winConfig>
```

I hope it helps!

**Comment by hannesN** [comment]
It helped! Thank you very much.
